"""Add order_number and catering fields to orders table

Revision ID: be1f556407ed
Revises: 85bc5107e44f
Create Date: 2025-10-25 23:40:11.699181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be1f556407ed'
down_revision = '85bc5107e44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servings_per_unit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('special_instructions', sa.Text(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('event_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('event_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('guest_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('special_requirements', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('estimated_total', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('final_total', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('deposit_paid', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('deposit_paid')
        batch_op.drop_column('final_total')
        batch_op.drop_column('estimated_total')
        batch_op.drop_column('special_requirements')
        batch_op.drop_column('guest_count')
        batch_op.drop_column('delivery_instructions')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('event_time')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_name')
        batch_op.drop_column('order_number')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('special_instructions')
        batch_op.drop_column('servings_per_unit')

    # ### end Alembic commands ###
